### ISSUE TITLE
==> ERROR: 'pacman' failed to install missing dependencies.

### ISSUE THREAD

**Issue by amadin** [KaOS-Community-Packages/minetest#1] opened 2018-03-02 22:28 UTC
live  ~  minetest-master  makepkg -si

**Comment by demmm** [comment] 2018-03-02 23:14
Did you actually look about this package?  README has all the info you need.
https://github.com/KaOS-Community-Packages/minetest
Not a bug, closing.

**Closed as completed by demmm** 2018-03-02 23:14 UTC
